name = "google-drive-index"
compatibility_date = "2026-01-02"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "drive-index-db"
database_id = "21dc2911-5a07-4dd1-be44-457533ed13ec"
