name = "google-drive-index"
compatibility_date = "2026-01-02"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "drive-index-db"
database_id = "bc93bf05-d222-4ae8-9179-1eef36a52fd8"
